# Generated by Django 5.2.8 on 2025-11-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
