# Generated by Django 5.2.8 on 2025-11-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_content_is_sent_content_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='app.topic')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='recipients', to='app.subscriber'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
