# Generated by Django 5.2.8 on 2025-11-25 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_subscriber_content_recipients_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='app.topic'),
        ),
    ]
