# Generated by Django 5.2.8 on 2025-11-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_subscriber_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='recipients',
        ),
    ]
